language: erlang
script: make
otp_release:
  - R16B
before_install:
  - mkdir -p vendor/elixir
  - wget -q https://github.com/elixir-lang/elixir/archive/v0.9.1.zip && unzip -qq v0.9.1.zip -d vendor/elixir
  - export PATH="$PATH:$PWD/vendor/elixir/bin"
